name       : frameworkintegration
version    : 5.44.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/frameworkintegration-5.44.0.tar.xz : 81580924bfe4f143ec72492c92476cc7b01ae5b6de67b0be092a370ad9523883
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
