name       : frameworkintegration
version    : 5.43.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/frameworkintegration-5.43.0.tar.xz : 80ef02d0f590c018321a1dca97dff8e40520e82cf5331d5591b85faa29995762
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
