name       : frameworkintegration
version    : 5.94.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/frameworkintegration-5.94.0.tar.xz : 9a64abebf8d242765ae759611fc9819a03403047ed56b8dd71aba7a0bbb4faa6
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : programming.library
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
optimize   : lto
builddeps  :
    - attica-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
