name       : frameworkintegration
version    : 5.56.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/frameworkintegration-5.56.0.tar.xz : ee8d46b629a95e49fda80e50ba8863504a6c463fec887f83370b7e7977db80f5
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
