name       : frameworkintegration
version    : 5.62.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/frameworkintegration-5.62.0.tar.xz : 0d43d6cd008359eac4840c8b6e12d2b17eeb53c95111af1f7e8ca6ae8e6aca2c
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
