name       : frameworkintegration
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/frameworkintegration-5.32.0.tar.xz : 8a5ff514aaa73c4fbf616be45be9be9a2699d80c3409ccc749c8d07709635a08
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : programming
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
