name       : frameworkintegration
version    : 5.58.0
release    : 25
source     :
    - https://download.kde.org/stable/frameworks/5.58/frameworkintegration-5.58.0.tar.xz : fe2449263d324bfbe43a9c6f50115fbe3b0628516d2b2010e6a9049ead3e7541
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Packport-in-the-new-location-for-knsrc-files.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
