name       : frameworkintegration
version    : 5.57.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/frameworkintegration-5.57.0.tar.xz : 9c5850c1d41900bcb81e7929d54856d0cdd2565a276e5e262f624eb1217cbb78
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
