name       : frameworkintegration
version    : 5.81.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/frameworkintegration-5.81.0.tar.xz : 3b98768f0bbb6f3c427a74504eae7d3045d3af20946d3bc6f5937f6206a88b6d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : programming.library
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
optimize   : lto
builddeps  :
    - attica-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
