name       : frameworkintegration
version    : 5.88.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.88/frameworkintegration-5.88.0.tar.xz : 423b05d84364956cac1eaa01669aa25db6a78ad46f8557eb2766e326d7bf4191
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : programming.library
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
optimize   : lto
builddeps  :
    - attica-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
