name       : frameworkintegration
version    : 5.66.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/frameworkintegration-5.66.0.tar.xz : 55c01613436781d74652bef19fc594448cdee4c002d5e1713b583473455f54d8
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
builddeps  :
    - extra-cmake-modules
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
